# Generated by Django 3.2 on 2021-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210519_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
