# Generated by Django 3.2 on 2021-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210528_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
